import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Nav from "./components/Navigation"
import Footer from "./components/Footer"

import "./globals.css";
import { CalendarSearch } from "lucide-react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  
  children,
}: Readonly<{
  
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     
      <body className={inter.className}>  
      <Nav/>
      {children}
       <Footer />
      </body>
    </html>
  );
}
